---
author: 
 - 'Allan Victor Almeida Faria (190127180)'
 - 'Ananda Alme de Sá (150117345)'
 - 'Bruno Kevyn Andrade de Souza'
date: '21/02/2021'
documentclass: abntex2
classoption: 
- oneside
- brazil
papersize: a4
fontsize: 12pt
output: 
  pdf_document:
    includes:
      in_header: 'preamble.tex'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\selectlanguage{brazil}
  
<!-- # Retira espaço extra obsoleto entre as frases. -->
\frenchspacing

<!--   # ---------------------------------------------------------- -->
<!--   # == ELEMENTOS PRÉ-TEXTUAIS -->
<!--   # ---------------------------------------------------------- -->
<!--   # \pretextual -->
<!--   # ---------------------------------------------------------- -->


<!--   # ---------------------------------------------------------- -->
<!--   # Capa -->
<!--   # ---------------------------------------------------------- -->
  \imprimircapa

<!--   # ---------------------------------------------------------- -->
<!--   # Folha de rosto (o * indica que haverá a ficha bibliográfica) -->
<!--   # ---------------------------------------------------------- -->
  \imprimirfolhaderosto*

<!--   # ---------------------------------------------------------- -->
<!--   # Resumo -->
<!--   # ---------------------------------------------------------- -->
```{r child = 'pretextuais/resumo.Rmd'}
```

<!--   # ---------------------------------------------------------- -->
<!--   # inserir listas de ilustrações, tabelas e quadros -->
<!--   # ---------------------------------------------------------- -->
```{r child = 'pretextuais/itq.Rmd'}
```

<!--   # ---------------------------------------------------------- -->
<!--   # inserir listas de siglas -->
<!--   # ---------------------------------------------------------- -->
```{r child = 'pretextuais/siglas.Rmd'}
```

<!--   # ---------------------------------------------------------- -->
<!--   # inserir o sumario -->
<!--   # ---------------------------------------------------------- -->
  \pdfbookmark[0]{\contentsname}{toc}
  \tableofcontents*
  \cleardoublepage

<!--   # ---------------------------------------------------------- -->
<!--   # == ELEMENTOS TEXTUAIS -->
<!--   # ---------------------------------------------------------- --> 
\textual

<!--   # ---------------------------------------------------------- -->
<!--   # Introdução -->
<!--   # ---------------------------------------------------------- --> 
```{r child = 'textuais/introducao.Rmd'}
```

<!--   # ---------------------------------------------------------- --> 
<!--   # == PARTE - preparação da pesquisa --> 
<!--   # ---------------------------------------------------------- --> 
\part{Metodologia}

<!--   # ---------------------------------------------------------- --> 
<!--   # Capitulo com exemplos de comandos inseridos de arquivo externo  -->
<!--   # ---------------------------------------------------------- --> 
```{r child = 'textuais/metodos.Rmd'}
```


<!--   # ---------------------------------------------------------- --> 
<!--   # == PARTE - Resultados --> 
<!--   # ---------------------------------------------------------- --> 
\part{Resultados}

<!--   # Capitulo de revisão de literatura --> 
<!--   # ---------------------------------------------------------- --> 
```{r child = 'textuais/resultados.Rmd'}
```

<!--   # ---------------------------------------------------------- --> 
<!--   # == PARTE - Finaliza a parte no bookmark do PDF --> 
<!--   #    para que se inicie o bookmark na raiz e adiciona espaço de parte no Sumário --> 
<!--   # ---------------------------------------------------------- --> 
\phantompart


<!--   # ---------------------------------------------------------- --> 
<!--   # Conclusão --> 
<!--   # ---------------------------------------------------------- --> 
```{r child = 'textuais/conclusao.Rmd'}
```

<!--   # ---------------------------------------------------------- --> 
<!--   # == ELEMENTOS PÓS-TEXTUAIS --> 
<!--   # ---------------------------------------------------------- --> 
\postextual

<!--   # ---------------------------------------------------------- --> 
<!--   # Referências bibliográficas --> 
<!--   # ---------------------------------------------------------- --> 
\bibliography{bib/referencia}


<!--   # ---------------------------------------------------------- --> 
<!--   # == ANEXOS --> 
<!--   # ---------------------------------------------------------- --> 
\begin{anexosenv}

  \partanexos

```{r child = 'postextuais/anexo1.Rmd'}
```

\end{anexosenv}

<!--   #--------------------------------------------------------------------- --> 
<!--   # == INDICE REMISSIVO --> 
<!--   #--------------------------------------------------------------------- --> 
\phantompart

